version: '2'
services:
  https-portal:
    image: steveltn/https-portal:1
    volumes:
    - ./https-portal/ssl:/var/lib/https-portal
    - ./https-portal/letsencrypt:/etc/letsencrypt
    ports:
    - 80:80
    - 443:443
    links:
    - nginx:nginx
    restart: always
    environment:
      DOMAINS: 'hipsty.local.net: -> http://phpfpm:80'
      STAGE: 'local'
      # FORCE_RENEW: 'true'

  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./nginx/conf.d/local:/etc/nginx/conf.d
    - ./nginx/log:/var/log/nginx
    - ./laravel:/var/www/laravel
    - ./nginx/ssl:/var/lib/https-portal
    links:
    - phpfpm:phpfpm
    - mysql:mysql
    restart: always

  phpfpm:
    image: php:7.2-fpm-alpine
    build: 
      context: ./php-fpm
    volumes:
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf # 全体の設定ファイル
      - ./php-fpm/php-fpm.d:/usr/local/etc/php-fpm.d # プール向け設定ファイル
      - ./php-fpm/log/php-fpm:/usr/local/var/log
      - ./php-fpm/log/php:/var/log/php
      - ./laravel:/var/www/laravel
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql:/etc/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER:     user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: hiphop_station
    restart: always